### ISSUE TITLE
PyEMD indexer usage

### ISSUE THREAD

**Issue by denisb411** [lgalke/vec4ir#1]
Hello,

I'm trying to find the usage of the EMD (wmd) algorithm but I didn't find any import of the pyemd library on the code.
Is there already any implementation of this usage?

Thanks,
Denis

**Comment by lgalke** [comment]
Hello @denisb411 ,

The `pyemd` was used by `gensim` to compute the word-movers distance. Still, the newest implementation of wmdistance in `gensim` might not depend on `pyemd` anymore; there was an update few weeks ago to the word-movers distance computation in `gensim`.

**Comment by lgalke** [comment]
To answer the question, we reuse the [gensim](https://radimrehurek.com/gensim/) implementation of Word mover's distance.

**Comment by lgalke** [comment]
@denisb411 a short notice: gensim still requires pyemd to compute the Word Mover's distance. However, pyemd is now removed from the requirements because its installation via pip depends on prevalence of python development symbols (usually in something like `python3-dev[el]` package).
