### ISSUE TITLE
oov Words

### ISSUE THREAD

**Issue by TamouzeAssi** [lgalke/vec4ir#4]
MY question in not about an issue. It is about how do you deal with the OOV words?

**Comment by lgalke** [comment]
Hello @TamouzeAssi,

There is no special treatment for UNK tokens so far. In the default case, they are ignored.
For an (unsupervised) retrieval task, I found that it was not helpful to assign a specific vector to those unknown tokens. Also, the effect of up-training pre-trained word embeddings on the concrete corpus was marginal in my experiments.

You can pass a specific `analyzer` to most retrieval models, in which you could map unknown tokens to a special `<UNK>` token and, for instance, init it with a random-but-fixed random vector in your embedding.

Also: there is a small `uptrain` function in `postprocessing.py`. which you can use to load a pre-trained word embedding and perform some epochs of uptraining on your corpus. By specifying a `lockf` freezing parameter, you can chose whether you want to leave the original vectors unchanged or make only minor changes. It is only a wrapper for the `gensim` functionality though.

Hope I could help!

**Comment by lgalke** [comment]
Regarding the up-training, you can find a Table A.6 with some experiments in my [master's thesis](http://lpag.de/theses/masters.pdf). I hope your question is answered, feel free to re-open if not.
