### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by kamrul29** [lgalke/vec4ir#6]
can you share full working source code with data please? as a beginner i am getting too many errors,now stuck at wcd = WordCentroidDistance(model)
AttributeError: 'Word2Vec' object has no attribute 'index2word'

**Comment by lgalke** [comment]
Thanks for your interest.

See `tests/test_vec4ir.py` for examples:

```python
def test_word2vec():
    model = Word2Vec([doc.split() for doc in documents], iter=1, min_count=1)
    match_op = Matching()
    wcd = WordCentroidDistance(model.wv)
    retrieval = Retrieval(wcd, matching=match_op)
    retrieval.fit(documents)
    result = retrieval.query('dog')
    assert result[0] == 0
```

The WordCentroidDistance constructor expects the word vectors part (`wv`) of the gensim model. I might want to introduce a better warning message.

**Comment by kamrul29** [comment]
It would be so helpful if you make a query expansion model with a set of inputs and outputs for the correspondent input set. Now stuck at transform method, If we clearly see a proper model of your query expansion system with simple inputs and output then it will be great

**Comment by lgalke** [comment]
Ah I see. Will try to include a proper test for query expansion and let you know as soon as there are updates. Are you implementing an own query expansion technique or trying to apply the ones shipped?

**Comment by kamrul29** [comment]
I am trying to implement your process and aiming to gain knowledge from your processes so that in future i can be able to build more improved query expansion model

**Comment by kamrul29** [comment]
So far i have tried to implement many functions you wrote but unable to do it,, so i asked for a full code with input and output so that it will be more helpful,thank you

**Comment by lgalke** [comment]
575deca I added tests for query expansion and fixed some minor issues with the embedded-query-language model expansion. In principle a query expansion class should satisfy the following interface:

- `fit(raw_documents) -> self` Adapt internal attributes to corpus (if necessary). Always return `self`.
- `transform(query:str) -> expanded_query:str` A method that takes a string and expands it.

As usual all configuration happens in `__init__`. The two provided query expansion methods, for instance, take a word embedding as input which they use for query expansion.

Hope I could help
