### ISSUE TITLE
CLI : vec4ir-evaluate not running

### ISSUE THREAD

**Issue by itzpc** [lgalke/vec4ir#8]
When I try to run CLI vec4ir-evaluate, I get the following error

` YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe.`
`KeyError: 'ntcir2'`

**Comment by lgalke** [comment]
Hi @itzpc 

The dataset key needs to be defined in your config.yml file. I provided an [exemplary config.yml](
https://github.com/lgalke/vec4ir/blob/master/config.yml) file in the repo but you would need to create your own, eg by copying and adjusting the file paths.

Let me know if I can help with anything else!

**Comment by lgalke** [comment]
I see that there was still an old default value for the `--dataset` argument. I removed this default and made the dataset argument *required* instead. 5f2f01f

**Comment by lgalke** [comment]
If you want to run vec4ir on your own dataset, I'd recommend the QuadflorLike format as described [here](https://github.com/lgalke/vec4ir/blob/master/devguide.md#quadflor-like-dataset-format).
It is easier to set up manually compared to the format used for NTCIR2.

**Comment by itzpc** [comment]
Hey @lgalke  thank you for your quick response. I will look into it and will update you. Thanks a lot for developing this package. It is rally useful in many applications. #8 closed.
